### PR TITLE
Update hooks-overview.md

### PR DESCRIPTION
**Pull request by DaerusX**
修改了歧义，原来的文本有错误

### CODE REVIEW

**Comment by QC-L** [comment]
有什么歧义？

**Comment by DaerusX** [comment]
原意为hook不在class内工作 翻译为hook不能在class内工作 会让人误解



---Original---
From: "QiChang ***@***.***&gt;
Date: Tue, Aug 3, 2021 11:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [reactjs/zh-hans.reactjs.org] Update hooks-overview.md (#561)




 
有什么歧义？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DaerusX** [comment]
I don't work 和 I can't work 是不一样的



---Original---
From: "QiChang ***@***.***&gt;
Date: Tue, Aug 3, 2021 11:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [reactjs/zh-hans.reactjs.org] Update hooks-overview.md (#561)




 
有什么歧义？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by QC-L** [comment]
我们一起讨论过，感觉并不需要修改~

**Pull request closed without merging**
